// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package ai

import (
	fmt "fmt"

	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *AiReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AiReq[number], err)
}

func (x *AiReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v HistoryItem
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.History = append(x.History, &v)
	return offset, nil
}

func (x *AiReq) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.ProjectId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *HistoryItem) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_HistoryItem[number], err)
}

func (x *HistoryItem) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Question, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *HistoryItem) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Role, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AiResp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_AiResp[number], err)
}

func (x *AiResp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Answer, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *AiReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *AiReq) fastWriteField1(buf []byte) (offset int) {
	if x.History == nil {
		return offset
	}
	for i := range x.GetHistory() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetHistory()[i])
	}
	return offset
}

func (x *AiReq) fastWriteField2(buf []byte) (offset int) {
	if x.ProjectId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetProjectId())
	return offset
}

func (x *HistoryItem) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *HistoryItem) fastWriteField1(buf []byte) (offset int) {
	if x.Question == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetQuestion())
	return offset
}

func (x *HistoryItem) fastWriteField2(buf []byte) (offset int) {
	if x.Role == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetRole())
	return offset
}

func (x *AiResp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *AiResp) fastWriteField1(buf []byte) (offset int) {
	if x.Answer == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetAnswer())
	return offset
}

func (x *AiReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *AiReq) sizeField1() (n int) {
	if x.History == nil {
		return n
	}
	for i := range x.GetHistory() {
		n += fastpb.SizeMessage(1, x.GetHistory()[i])
	}
	return n
}

func (x *AiReq) sizeField2() (n int) {
	if x.ProjectId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetProjectId())
	return n
}

func (x *HistoryItem) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *HistoryItem) sizeField1() (n int) {
	if x.Question == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetQuestion())
	return n
}

func (x *HistoryItem) sizeField2() (n int) {
	if x.Role == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetRole())
	return n
}

func (x *AiResp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *AiResp) sizeField1() (n int) {
	if x.Answer == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetAnswer())
	return n
}

var fieldIDToName_AiReq = map[int32]string{
	1: "History",
	2: "ProjectId",
}

var fieldIDToName_HistoryItem = map[int32]string{
	1: "Question",
	2: "Role",
}

var fieldIDToName_AiResp = map[int32]string{
	1: "Answer",
}
