// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	app "github.com/MoScenix/ai-code/app/bff/biz/router/app"
	user "github.com/MoScenix/ai-code/app/bff/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	app.Register(r)

	user.Register(r)
}
